application: proyectoals
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /templates
  static_dir: templates
  application_readable: true

- url: /
  script: handlers.main.app

- url: /videojuego/nuevo
  script: handlers.videojuego.add.app
  login: required

- url: /videojuego/elimina
  script: handlers.videojuego.delete.app
  login: required

- url: /videojuego/modifica
  script: handlers.videojuego.modify.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"

- name:    PIL
  version: "latest"

